### ISSUE TITLE
[ERROR] json: cannot unmarshal string into Go struct field .mail.to of type []string

### ISSUE THREAD

**Issue by w9w** [firefart/websitewatcher#2]
Hi, although configuration file was set correctly, a tool outputs the following error:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/38838852/173179584-6152b065-52b5-4bf2-934e-744153b8db4d.png">

**Comment by firefart** [comment]
hi, looks like you defined the `to` in the config as a string instead of an array.

the correct syntax is
`"to": ["bbb@bbb.com", "ccc@ccc.com"],`
